name: $(Date:yyyyMMdd).$(BuildID)

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04

  strategy:
    matrix:
      GCC:
        CC: gcc
        CXX: g++
      Clang:
        CC: clang
        CXX: clang++

  steps:
  - script: |
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Debug ..
    displayName: Generate

  - script: |
      cd build
      cmake --build .
    displayName: Build

  - script: |
      cd build
      ctest -V --output-on-failure --interactive-debug-mode 0 -C Debug
    displayName: Test

- job: Windows
  pool:
    vmImage: vs2017-win2016

  strategy:
    matrix:
      x86:
        target_arch: x86
      x64:
        target_arch: amd64

  steps:
  - task: BatchScript@1
    inputs:
      filename: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat
      arguments: -no_logo -arch=$(target_arch)
      modifyEnvironment: true
    displayName: Setup Environment Variables

  - script: |
      mkdir build
      cd build
      cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
    displayName: Generate

  - script: |
      cd build
      cmake --build .
    displayName: Build

  - script: |
      cd build
      ctest -V --output-on-failure --interactive-debug-mode 0 -C Debug
    displayName: Test
